import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8');
const background = read('../src/background.js');
const context = vm.createContext({});
vm.runInContext(background.slice(0, background.indexOf('function storageGet(')), context);
const marker = '__MKP_PHONE_PLUGIN__';
let runtime = context.buildUserScriptCode(marker, '__MKP_NAME__', 'phone-1.0.0');
runtime = runtime.replace('(() => {', 'async function runPlugin(pluginName, run) {')
  .replace('  const pluginName = "__MKP_NAME__";', '')
  .replace(marker, 'await run(api);')
  .replace('    if (window.__misskeyPatcherUserRouteHooksInstalled) return;', '')
  .replace('  main();\n})();', '  return main();\n}');

let content = read('../src/content.js');
const storageStart = content.indexOf('  function getChromeStorage()');
const storageEnd = content.indexOf('  function hostIsAllowed(', storageStart);
content = content.slice(0, storageStart) + `
  function getChromeStorage() {
    return Promise.resolve({ ...DEFAULTS, ...readSettings() });
  }

  function setCurrentInstanceSettings(nextSettings, callback) {
    try {
      localStorage.setItem(SETTINGS_KEY, JSON.stringify({ ...readSettings(), ...nextSettings }));
      callback?.();
    } catch (error) {
      toast('設定を保存できませんでした: ' + error.message);
    }
  }

` + content.slice(storageEnd);
const syncStart = content.indexOf('  function syncUserScripts(');
const syncEnd = content.indexOf('  async function openInlineSettings(', syncStart);
content = content.slice(0, syncStart) + `
  function syncUserScripts(callback) {
    callback?.({ ok: true, count: normalizePlugins(readSettings()).filter(p => p.enabled && p.code.trim()).length });
  }

` + content.slice(syncEnd);
content = content.replace("chrome.runtime?.getManifest?.().version ?? 'dev'", "'phone-1.0.0'")
  .replaceAll('Chrome拡張機能の設定を開き、MisskeyToolsを開き、<br>「ユーザー スクリプトを許可する」を有効にしてください。', 'プラグインを保存した後、このページを再読み込みしてください。')
  .replace('保存しました。追加 JS の登録には Chrome の Allow User Scripts または Developer mode が必要です。', '保存しました。ページを再読み込みしてください。')
  .replace("    form.elements.namedItem('pluginList').focus();\n  }\n\n  function onRouteChange", "    root.querySelector('button')?.focus();\n  }\n\n  function onRouteChange");
content = content.replace('    state.active = true;', `    installPhoneStyle();
    state.active = true;`);
content = content.replace('  main();', `  main().then(async () => {
    if (!state.active) return;
    const settings = await getChromeStorage();
    for (const plugin of normalizePlugins(settings)) {
      if (!plugin.enabled || !plugin.code.trim()) continue;
      try {
        const execute = new AsyncFunction('window', 'document', 'api', plugin.code);
        await runPlugin(plugin.name, api => execute(window, document, api));
      } catch (error) {
        console.error('[Misskey Patcher phone] plugin failed:', plugin.name, error);
        toast(plugin.name + ': ' + error.message);
      }
    }
  }).catch(error => console.error('[Misskey Patcher phone]', error));`);

const output = `// ==UserScript==
// @name         MisskeyPatcher Phone
// @namespace    MisskeyPatcher
// @version      1.0.0
// @description  MisskeyPatcher plugin API and settings for mobile browsers
// @match        https://*/*
// @run-at       document-start
// @grant        none
// ==/UserScript==
// Generated by phone_js/build.mjs. Run in the page's main world.
(() => {
'use strict';
if (window.__misskeyPatcherPhoneInstalled) return;
window.__misskeyPatcherPhoneInstalled = true;
const SETTINGS_KEY = 'misskey-patcher:phone:settings';
const AsyncFunction = Object.getPrototypeOf(async function () {}).constructor;
function readSettings() {
  try { return JSON.parse(localStorage.getItem(SETTINGS_KEY) || '{}') || {}; }
  catch (error) { console.warn('[Misskey Patcher phone] settings unavailable', error); return {}; }
}
function installPhoneStyle() {
  const style = document.createElement('style');
  style.id = 'mkp-phone-ui-style';
  style.textContent = ${JSON.stringify(read('../src/ui.css') + '\n' + read('../src/patch.css'))};
  (document.head || document.documentElement).append(style);
}
${read('../src/page-bridge.js')}
${runtime}
window.MisskeyPatcher = Object.freeze({ runPlugin, version: 'phone-1.0.0' });
${content}
})();
`;
writeFileSync(fileURLToPath(new URL('background.js', import.meta.url)), output);
console.log('Generated phone_js/background.js');
